version: '3.9'

services:
  db:
   container_name: ${DB_CONTAINER_NAME}
   build: 
     context: .
     dockerfile: metflix.Dockerfile
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: ${DB_PSW}
   ports:
      - ${DB_PORTS}

  adminer:
    container_name: ${ADMINER_CONTAINER_NAME}
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORTS}